# Generated by Django 4.1.1 on 2022-10-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
